In [19]:
import torch

In [20]:
#학습데이터 생성
x_train = torch.FloatTensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],
                             [1,2,5,6],[1,6,6,6],[1,7,7,7]])
y_train = torch.FloatTensor([[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],
                             [1,0,0],[1,0,0]])

#W, b 초기화 / learning late 설정
W = torch.zeros(4,3,requires_grad=True)
b = torch.zeros(1,3,requires_grad=True)
optimizer = torch.optim.Adam([W,b],lr = 0.1)

In [21]:
for epoch in range(3001): #반복횟수 설정
    #Hypothesis, cost 설정
    hypothesis = torch.softmax(torch.mm(x_train, W)+b, dim=1)
    cost = -torch.mean(torch.sum(y_train*torch.log(hypothesis), dim=1))
    
    #Optimizer를 이용한 경사 계산 및 W, b 업데이트
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    #학습이 잘 되는지 확인하기위한 내용 출력
    if epoch % 100 == 0:
        print( 'epoch: {}, cost: {:.6f}'.format(epoch, cost.item()))

epoch: 0, cost: 1.098612
epoch: 100, cost: 0.279874
epoch: 200, cost: 0.162209
epoch: 300, cost: 0.105262
epoch: 400, cost: 0.074083
epoch: 500, cost: 0.055093
epoch: 600, cost: 0.042634
epoch: 700, cost: 0.034003
epoch: 800, cost: 0.027768
epoch: 900, cost: 0.023111
epoch: 1000, cost: 0.019535
epoch: 1100, cost: 0.016727
epoch: 1200, cost: 0.014479
epoch: 1300, cost: 0.012650
epoch: 1400, cost: 0.011140
epoch: 1500, cost: 0.009879
epoch: 1600, cost: 0.008813
epoch: 1700, cost: 0.007905
epoch: 1800, cost: 0.007124
epoch: 1900, cost: 0.006447
epoch: 2000, cost: 0.005856
epoch: 2100, cost: 0.005338
epoch: 2200, cost: 0.004881
epoch: 2300, cost: 0.004475
epoch: 2400, cost: 0.004113
epoch: 2500, cost: 0.003789
epoch: 2600, cost: 0.003499
epoch: 2700, cost: 0.003236
epoch: 2800, cost: 0.002999
epoch: 2900, cost: 0.002784
epoch: 3000, cost: 0.002588


In [22]:
#x 가 [1,11,10,9], [1,3,4,3], [1,1,0,1] 일 때, y값 확인
W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
test_all = torch.softmax(torch.mm(x_test, W)+b, dim=1)
print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[1.0000e+00, 5.5165e-19, 7.0151e-38],
        [1.4800e-02, 7.4294e-01, 2.4226e-01],
        [1.2256e-33, 9.0835e-12, 1.0000e+00]])
tensor([0, 1, 2])


### 조금더깔끔하게Softmax

In [23]:
import torch.nn.functional as F
import torch.nn as nn

In [24]:
#학습데이터 생성
x_train = torch.FloatTensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],
                             [1,2,5,6],[1,6,6,6],[1,7,7,7]])
y_train = torch.LongTensor([2,2,2,1,1,1,0,0])

#어차피 맨날 쓰는 W와 b. nn.Linear로 대체하자!
model = nn.Linear(4,3)
optimizer = torch.optim.Adam(model.parameters(),lr=1)

In [25]:
for epoch in range(3001): #반복횟수 설정
    #Hypothesis, cost 설정
    z = model(x_train)
    cost = F.cross_entropy(z, y_train)
    
    #Optimizer를 이용한 경사 계산 및 W, b 업데이트
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    #학습이 잘 되는지 확인하기위한 내용 출력
    if epoch % 100 == 0:
        print( 'epoch: {}, cost: {:.6f}'.format(epoch, cost.item()))

epoch: 0, cost: 1.720316
epoch: 100, cost: 0.093263
epoch: 200, cost: 0.051158
epoch: 300, cost: 0.031883
epoch: 400, cost: 0.021796
epoch: 500, cost: 0.015901
epoch: 600, cost: 0.012155
epoch: 700, cost: 0.009618
epoch: 800, cost: 0.007814
epoch: 900, cost: 0.006481
epoch: 1000, cost: 0.005467
epoch: 1100, cost: 0.004675
epoch: 1200, cost: 0.004043
epoch: 1300, cost: 0.003530
epoch: 1400, cost: 0.003108
epoch: 1500, cost: 0.002756
epoch: 1600, cost: 0.002459
epoch: 1700, cost: 0.002206
epoch: 1800, cost: 0.001988
epoch: 1900, cost: 0.001800
epoch: 2000, cost: 0.001635
epoch: 2100, cost: 0.001491
epoch: 2200, cost: 0.001363
epoch: 2300, cost: 0.001250
epoch: 2400, cost: 0.001150
epoch: 2500, cost: 0.001059
epoch: 2600, cost: 0.000978
epoch: 2700, cost: 0.000905
epoch: 2800, cost: 0.000839
epoch: 2900, cost: 0.000779
epoch: 3000, cost: 0.000724


### Softmax Regression with sklearn

In [26]:
import numpy as np
from sklearn.linear_model import LogisticRegression

In [15]:
x_train = np.array([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
 [1,2,5,6], [1,6,6,6], [1,7,7,7] ])

# y에 0, 1, 2 등 둘 이상의 class가 존재 => softmax regression
y_train = np.array([ 2, 2, 2, 1, 1, 1, 0, 0 ])

In [27]:
logistic = LogisticRegression() # 모델 생성
logistic.fit(x_train, y_train) # 학습

pred = logistic.predict([[1,11,10,9], [1,3,4,3], [1,1,0,1]]) # test case (값 예측)
print(pred) # 출력

[0 2 2]
